name: Deploy to staging
on:
  push:
    branches: ["main"]

jobs:
  runs-on: ubuntu-latest
  redeploy_Everything:
    name: Deploying the Everything to staging cluster
    steps:
      - run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          ssh -i ~/ssh_key ubuntu@15.207.79.102
          cd week25-2 && git pull
          npm install
          npm run build
          pm2 restart all



